src/Entity/LongueurPartie.php
<?php

namespace App\Entity;

use App\Repository\LongueurPartieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LongueurPartieRepository::class)]
class LongueurPartie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $nombre_etape = null;

    /**
     * @var Collection<int, Partie>
     */
    #[ORM\OneToMany(targetEntity: Partie::class, mappedBy: 'longueur_partie')]
    private Collection $parties;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNombreEtape(): ?int
    {
        return $this->nombre_etape;
    }

    public function setNombreEtape(int $nombre_etape): static
    {
        $this->nombre_etape = $nombre_etape;

        return $this;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): static
    {
        if (!$this->parties->contains($party)) {
            $this->parties->add($party);
            $party->setLongueurPartie($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): static
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getLongueurPartie() === $this) {
                $party->setLongueurPartie(null);
            }
        }

        return $this;
    }
}

templates/partie_multi/lancer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une partie multijoueur{% endblock %}

{% block importmap %}
    <script src="{{ asset('appLancerPartie.js') }}"></script>
{% endblock %}

{% block body %}
    {% include 'partie_multi/modal_annulerPartie.html.twig' %}
   
    <input type="hidden" id="hidden_url_liste_joueurs" value= {{ url("app_partie-multi_liste_joueurs") }}/{{ partie.id }}  /> {#{{ partie.id }} #}
    <input type="hidden" id="hidden_etat_partie" value= {{ url("app_partie-multi_etat") }}/{{ partie.id }}  /> {#{{ partie.id }} #}
    <input type="hidden" id="hidden_url_jeu" value= {{ url("app_jouer_multi__jouer",{ codeConnexion:  partie.code_connexion } )  }}  />
    

    <span class="demarrage_messageBienvenue">Bienvenue sur la partie: </span> <span class="lancer_partie_mulitijoueur__codeConnexion"> {{ partie.code_connexion }} </span>

    <BR>
    <BR>

    <div id="corpsPageLancerPartie">
        {# Si la partie est dans l'état annulé: #}
        {% if etat_partie.id == code_partie_abondonnee %}
            Désolé, la partie a été annulée. Pour lancer vous-même une partie, allez dans le menu général et cliquez sur: Créer/lancer une partie multijoueur

        {# Si la partie est dans l'état: en cours de connexion #}
        {% else %}
            <div>
                <span class="titre">Pour inviter des gens:</span>
                
                <table class="table lancer_partie_mulitijoueur__tableau_lien">
                    <tr>
                        <td colspan=3 class="ligne_communication_lien">
                            <ul class="lancer_partie_mulitijoueur__ul">
                                <li>Communiquez leur simplement ce lien: </li> 
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td class="cellule_lien_et_code">
                            <a href="{{ url("app_partie-multi_rejoindre",{ codeConnexion:  partie.code_connexion  } )  }}" id="adrACopier"> {{ url("app_partie-multi_rejoindre",{ codeConnexion:  partie.code_connexion  } ) }}</a>
                        </td>

                        <td class="cellule_boutonCopier">
                            <button class="boutonCopier" type="button" aria-label="Copier" title="Copier l'url de la partie dans le presse-papiers" 
                                onclick="copierPressePapier()"> 
                                <i class="fa-regular fa-copy"  aria-hidden="true"></i>
                            </button>
                        </td>
                        
                        <td>
                            <label id="TextElCopie" class="cellule_infoCopie"></label>
                        </td>
                    <tr>
                        <td colspan=3 class="ligne_communication_lien">
                            <ul class="lancer_partie_mulitijoueur__ul">
                                <li>Ou ce code de connexion: </li> 
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="lancer_partie_mulitijoueur__codeConnexionPetit" id="codeACopier">{{ partie.code_connexion  }}</span>
                        </td>
                        
                        <td class="cellule_boutonCopier">
                            <button class="boutonCopier" type="button" aria-label="Copier" title="Copier le code dans le presse-papiers" onclick="copierPressePapier('codeACopier', 'TextElCopie2', 'innerText')"> 
                                <i class="fa-regular fa-copy" aria-hidden="true"></i>
                            </button>
                        </td>
                        
                        <td>
                            <label id="TextElCopie2" class="cellule_infoCopie"></label>
                        </td>
                    </tr>
                </table>
            </div>

            <BR>
            
            <div class="titre">
                Liste des joueurs déjà connectés:
            </div>
            
            <div id="idListeJoueur">
                {#Fait désormais avec un script Javascript #}
            </div>

            <button onclick="rafraichirTableauListeJoueurs()" class="btn btn-secondary center-block btn-sm">Rafraichir</button>
            <BR>
            <BR> 
            <BR>

            {% if estCreateur %}
                <a href="{{ path('app_jouer_multi__demarrer', { codeConnexion:  partie.code_connexion  } ) }}" class="btn btn-primary center-block btn-sm">Lancer la partie</a>
                
                <button type="button" class="btn btn-danger center-block btn-sm" 
                    data-bs-toggle="modal" data-bs-target="#idModalAnnulerPartie"
                    data-titre = "Confirmation d'annulation de partie" 
                    data-question = "Etes-vous sûr de vouloir annuler la partie ayant pour code: << {{ partie.code_connexion }} >> ?" 
                    data-route = {{ path('app_partie-multi_annuler', { codeConnexion:  partie.code_connexion  } ) }} >
                    Annuler la partie
                </button>

            {% else %}
                <p>Veuillez patienter, le créateur de la partie va lancer la partie d'ici quelques minutes</p>
                
                <button type="button" class="btn btn-danger center-block btn-sm" 
                    data-bs-toggle="modal" data-bs-target="#idModalAnnulerPartie"
                    data-titre = "Confirmation d'annulation de participation" 
                    data-question = "Etes-vous sûr de vouloir annuler votre participation à la partie: <BR><< {{ partie.code_connexion }} >> ?" 
                    data-route = {{ path('app_partie-multi_annuler-participation', { codeConnexion:  partie.code_connexion  } ) }} >
                    Annuler ma participation
                </button>
            {% endif %}
        {% endif %}
    </div>
    
    <script>
        const codePartieEnCours = {{ code_partie_en_cours }}
        const codePartieTerminee = {{ code_partie_terminee }}
        const codePartieEnCoursDeConnexion = {{ code_partie_en_cours_de_connexion }}
        const codePartieAbandonnee = {{ code_partie_abondonnee }}
        const codeConnexion = "{{ partie.code_connexion }}"
        
        rafraichirElementsPages(codePartieEnCours, codePartieTerminee, codePartieEnCoursDeConnexion, codePartieAbandonnee,codeConnexion)
        var rafraichissementElementsPage = setInterval(rafraichirElementsPages, 5000, codePartieEnCours, codePartieTerminee, codePartieEnCoursDeConnexion, codePartieAbandonnee, codeConnexion);
        
    </script>
{% endblock %}

templates/partie_multi/modal_annulerPartie.html.twig
  <!-- Modal -->
  <div class="modal fade" id="idModalAnnulerPartie" tabindex="-1" role="dialog" aria-labelledby="ModalAnnulerPartie" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="idModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Texte d'exemple
        </div>
        <div class="modal-footer">
          <button type="button" id="button_oui" class="btn btn-primary">Oui</button>
          <button type="button" id="button_non" class="btn btn-primary" data-bs-dismiss="modal">Non</button>
        </div>
      </div>
    </div>
  </div>


  <script>
    document.addEventListener("DOMContentLoaded", function () {  //Attend la fin du chargement du DOM
    var modal = document.getElementById("idModalAnnulerPartie");
    modal.addEventListener("show.bs.modal", function (event) {   //Evènement avant apparition de la modale
      var button = event.relatedTarget;                          //Bouton qui a déclenché la modale
      var title = button.getAttribute("data-titre");        
      var question = button.getAttribute("data-question");  
      var route = button.getAttribute("data-route");  

      var modalTitle = modal.querySelector(".modal-title");
      var modalBody = modal.querySelector(".modal-body");

      modalTitle.textContent = title;                            //Injecte le titre dans la modale
      modalBody.innerHTML = question;                            //Injecte le contenu dans la modale 

      var bouttonOui = document.getElementById('button_oui')

      bouttonOui.addEventListener('click', function () {
          //Appel de la route annuler en lui passant les paramètres  path('app_partie-multi_annuler', { codeConnexion:  partie.code_connexion  }
          window.location.href = route 
      }) 
    });
  });
</script>

templates/partie_multi/rejoindre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rejoindre une partie multijoueur{% endblock %}

{% block body %}
    {# Pour la gestion des fenêtres modales #}
    {% include 'partie_multi/partials/modal.html.twig' %}
    {% include 'partie_multi/partials/modal_img.html.twig' %}

<BR>
<BR>
    {% if partieARejoindre is not defined %}
        <div class="rejoindre_une_partie_multi__div_Principal">
            <h1 class="h3 mb-3 font-weight-normal">Rejoindre une partie: </h1> 
            <BR><BR>

            <div class="rejoindre_une_partie_multi__div_formulaire">
                <label for="id_code_connexion">Code de connexion:</label>
                <input type="text" id="id_code_connexion" class="form-control mb-3 " name="code_connexion" required minlength="19" maxlength="19" size="19" />
                <input type="hidden" id="id_chemin" value="{{ url('app_partie-multi_rejoindre', { codeConnexion: 100  }) }}">
            </div>
            
            <a href="#" id='id_lien' class="btn btn-primary">Information sur la partie</a>    
        </div>

        <script>
             document.getElementById('id_code_connexion').addEventListener('input', ()=>{
                 var inputValue = document.getElementById('id_code_connexion').value;
                 console.log(inputValue) ;
                 var lien = document.getElementById("id_lien");
                 var chemin = document.getElementById("id_chemin").value;
                 chemin = chemin.slice(0, chemin.length-3);                 //enlève le codeConnexion initial=>100 dans la variable chemin
                 lien.href= chemin + encodeURIComponent(inputValue);        //insère le code de connexion saisie par l'utilisateur dans le bouton "Information sur la partie"
            })
        </script>


    {% else %}    
        <div class="rejoindre_une_partie_multi__div_Principal">
            <h1 class="h3 mb-3 font-weight-normal">Rejoindre la partie: &nbsp;</h1> 
            <span class="rejoindre_une_partie_multi__codeConnexion"> {{partieARejoindre.codeConnexion}} </span>
            
            <BR><BR> 
            <div class="rejoindre_une_partie_multi__div_formulaire">
                <table class="table rejoindre_une_partie_multi__table">
                    <tbody>
                        <tr>
                            <th>Créateur:</th> 

                            <td class="rejoindre_nom" colspan="2"> 
                                {{ createur }} 
                            </td> 
                        </tr>
                        <tr>
                            <th>Genre littéraire:</th>    
                            
                                <td class="rejoindre_nom" > 
                                    {{ genreLitt.nom }} 
                                    <BR>
                                    <button type="button" class="btn btn-secondary center-block btn-sm" 
                                        data-bs-toggle="modal" 
                                        data-bs-target="#idExplicationGenreLitteraire"
                                        data-title="Explication du genre: {{ genreLitt.nom }}" data-content="{{ genreLitt.Commentaire|raw }}">
                                        Détails
                                    </button>
                                </td> 

                                <td class="rejoindre_illustration"> 
                                    <input type="image" class="bouton_image" id="modalImage" alt="Image" src="/images/genres_litteraires/{{ genreLitt.nom_image }}" 
                                        data-bs-toggle="modal" 
                                        data-bs-target="#imageModal" 
                                        data-image-titre="Illustration du genre: {{ genreLitt.nom }}"
                                        data-image="/images/genres_litteraires/{{ genreLitt.nom_image }}">
                                    <br>
                                </td>
                        </tr>
                        <tr>
                            <th>Durée:</th> 
                                <td colspan="2"> 
                                    {% if longueurPartie.nombreEtape > nbreEpreuveDansTableSCategorie %}
                                        {{ longueurPartie.nom }} => {{ nbreEpreuveDansTableSCategorie }} 
                                    {% else %}
                                        {{ longueurPartie.nom }} => {{ longueurPartie.nombreEtape }} étapes 
                                    {% endif %}
                                </td>
                        </tr>
                    </tbody>
                </table>
            </div>
                    
            <a href="{{ path('app_partie-multi_lancer', { codeConnexion:   partieARejoindre.codeConnexion  } ) }}" class="btn btn-primary center-block btn-sm">Rejoindre</a>
        </div>
    {% endif %}
<BR>
<BR>
<BR>
{% endblock %}