src/Entity/Partie.php
<?php

namespace App\Entity;

use App\Repository\PartieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartieRepository::class)]
class Partie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
  
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $code_connexion = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?LongueurPartie $longueur_partie = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?GenreLitteraire $genre_litteraire = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PartieEtat $etat = null;

    

    /**
     * @var Collection<int, PartieJoueur>
     */
    #[ORM\OneToMany(targetEntity: PartieJoueur::class, mappedBy: 'Partie')]
    private Collection $partieJoueurs;

    /**
     * @var Collection<int, PartieEpreuve>
     */
    #[ORM\OneToMany(targetEntity: PartieEpreuve::class, mappedBy: 'partie')]
    private Collection $partieEpreuves;

    public function __construct()
    {
        $this->partieEpreuves = new ArrayCollection();
        $this->partieJoueurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeConnexion(): ?string
    {
        return $this->code_connexion;
    }

    public function getCode_connexion(): ?string
    {
        return $this->code_connexion;
    }

    public function setCodeConnexion(string $code_connexion): static
    {
        $this->code_connexion = $code_connexion;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeImmutable
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeImmutable $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getLongueurPartie(): ?LongueurPartie
    {
        return $this->longueur_partie;
    }

    public function setLongueurPartie(?LongueurPartie $longueur_partie): static
    {
        $this->longueur_partie = $longueur_partie;

        return $this;
    }

    public function getGenreLitteraire(): ?GenreLitteraire
    {
        return $this->genre_litteraire;
    }

    public function setGenreLitteraire(?GenreLitteraire $genre_litteraire): static
    {
        $this->genre_litteraire = $genre_litteraire;

        return $this;
    }

    public function getEtat(): ?PartieEtat
    {
        return $this->etat;
    }

    public function setEtat(?PartieEtat $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, PartieEpreuve>
     */
    public function getPartieEpreuves(): Collection
    {
        return $this->partieEpreuves;
    }

    public function addPartieEpreufe(PartieEpreuve $partieEpreufe): static
    {
        if (!$this->partieEpreuves->contains($partieEpreufe)) {
            $this->partieEpreuves->add($partieEpreufe);
            $partieEpreufe->setPartie($this);
        }

        return $this;
    }

    public function removePartieEpreufe(PartieEpreuve $partieEpreufe): static
    {
        if ($this->partieEpreuves->removeElement($partieEpreufe)) {
            // set the owning side to null (unless already changed)
            if ($partieEpreufe->getIdPartie() === $this) {
                $partieEpreufe->setIdPartie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PartieJoueur>
     */
    public function getPartieJoueurs(): Collection
    {
        return $this->partieJoueurs;
    }

    public function addPartieJoueur(PartieJoueur $partieJoueur): static
    {
        if (!$this->partieJoueurs->contains($partieJoueur)) {
            $this->partieJoueurs->add($partieJoueur);
            $partieJoueur->setPartie($this);
        }

        return $this;
    }

    public function removePartieJoueur(PartieJoueur $partieJoueur): static
    {
        if ($this->partieJoueurs->removeElement($partieJoueur)) {
            // set the owning side to null (unless already changed)
            if ($partieJoueur->getPartie() === $this) {
                $partieJoueur->setPartie(null);
            }
        }

        return $this;
    }
}

src/Form/PartieType.php
<?php

namespace App\Form;

use App\Entity\GenreLitteraire;
use App\Entity\LongueurPartie;
use App\Entity\Partie;
use App\Entity\PartieEtat;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code_connexion')
            ->add('date_creation', null, [
                'widget' => 'single_text',
            ])
            ->add('longueur_partie', EntityType::class, [
                'class' => LongueurPartie::class,
                'choice_label' => 'id',
            ])
            ->add('genre_litteraire', EntityType::class, [
                'class' => GenreLitteraire::class,
                'choice_label' => 'id',
            ])
            ->add('etat', EntityType::class, [
                'class' => PartieEtat::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Partie::class,
        ]);
    }
}

src/Controller/PartieController.php
<?php

namespace App\Controller;

use App\Entity\Partie;
use App\Form\PartieType;
use App\Repository\PartieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/partie')]
class PartieController extends AbstractController
{
    #[Route('/', name: 'app_partie_index', methods: ['GET'])]
    public function index(PartieRepository $partieRepository): Response
    {
        return $this->render('partie/index.html.twig', [
            'parties' => $partieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_partie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $partie = new Partie();
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($partie);
            $entityManager->flush();

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('partie/new.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_show', methods: ['GET'])]
    public function show(Partie $partie): Response
    {
        return $this->render('partie/show.html.twig', [
            'partie' => $partie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_partie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Partie $partie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('partie/edit.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_delete', methods: ['POST'])]
    public function delete(Request $request, Partie $partie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partie->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($partie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/partie/_delete_form.html.twig
<form method="post" action="{{ path('app_partie_delete', {'id': partie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/partie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/partie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Partie{% endblock %}

{% block body %}
    <h1>Edit Partie</h1>

    {{ include('partie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_partie_index') }}">back to list</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}

templates/partie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie index{% endblock %}

{% block body %}
    <h1>Partie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code_connexion</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for partie in parties %}
            <tr>
                <td>{{ partie.id }}</td>
                <td>{{ partie.codeConnexion }}</td>
                <td>{{ partie.dateCreation ? partie.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_partie_show', {'id': partie.id}) }}">show</a>
                    <a href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_partie_new') }}">Create new</a>
{% endblock %}

templates/partie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Partie{% endblock %}

{% block body %}
    <h1>Create new Partie</h1>

    {{ include('partie/_form.html.twig') }}

    <a href="{{ path('app_partie_index') }}">back to list</a>
{% endblock %}

templates/partie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie{% endblock %}

{% block body %}
    <h1>Partie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partie.id }}</td>
            </tr>
            <tr>
                <th>Code_connexion</th>
                <td>{{ partie.codeConnexion }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ partie.dateCreation ? partie.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_partie_index') }}">back to list</a>

    <a href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}